// Autogenerated from Pigeon (v10.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN


/// The codec used by SKScanKitApi.
NSObject<FlutterMessageCodec> *SKScanKitApiGetCodec(void);

@protocol SKScanKitApi
/// @return `nil` only when `error != nil`.
- (nullable NSNumber *)createDefaultModeWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)disposeDefaultModeDId:(NSNumber *)dId error:(FlutterError *_Nullable *_Nonnull)error;
- (void)disposeCustomizedModeCusId:(NSNumber *)cusId error:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable NSNumber *)startScanDefaultId:(NSNumber *)defaultId type:(NSNumber *)type options:(NSDictionary<NSString *, id> *)options error:(FlutterError *_Nullable *_Nonnull)error;
- (void)pauseContinuouslyScanCusId:(NSNumber *)cusId error:(FlutterError *_Nullable *_Nonnull)error;
- (void)resumeContinuouslyScanCusId:(NSNumber *)cusId error:(FlutterError *_Nullable *_Nonnull)error;
- (void)switchLightCusId:(NSNumber *)cusId error:(FlutterError *_Nullable *_Nonnull)error;
- (void)pickPhotoCusId:(NSNumber *)cusId error:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable NSNumber *)getLightStatusCusId:(NSNumber *)cusId error:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable NSDictionary<NSString *, id> *)decodeYUVYuv:(FlutterStandardTypedData *)yuv width:(NSNumber *)width height:(NSNumber *)height options:(NSDictionary<NSString *, id> *)options error:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable NSDictionary<NSString *, id> *)decodeBytes:(FlutterStandardTypedData *)bytes width:(NSNumber *)width height:(NSNumber *)height options:(NSDictionary<NSString *, id> *)options error:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable NSDictionary<NSString *, id> *)decodeBitmapData:(FlutterStandardTypedData *)data options:(NSDictionary<NSString *, id> *)options error:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable FlutterStandardTypedData *)encodeContent:(NSString *)content width:(NSNumber *)width height:(NSNumber *)height options:(NSDictionary<NSString *, id> *)options error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void SKScanKitApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<SKScanKitApi> *_Nullable api);

NS_ASSUME_NONNULL_END
